// constants/staticData.js
// Static mock data for the worker pool.
// Mirrors the web app's ML match results page (Image 10).
// Replace with real API calls when the FastAPI ML engine is integrated.

export const MOCK_WORKERS = [
  {
    id: 'w1',
    full_name:    'Juan Dela Cruz',
    service:      'plumbing',
    verified:     true,
    ml_score:     78,
    skills:       ['Plumbing', 'Pipe Fitting', 'Water Heater'],
    location:     'Zone 1, Bulua, CDO',
    availability: 'Weekdays',
    jobs_done:    12,
    years_exp:    5,
    daily_rate:   550,
    rating:       4.8,
  },
  {
    id: 'w2',
    full_name:    'Rosa Lim',
    service:      'electrical',
    verified:     true,
    ml_score:     55,
    skills:       ['Electrical', 'Wiring', 'Circuit Breaker', 'Panel Box'],
    location:     'Zone 4, Bulua, CDO',
    availability: 'Weekdays',
    jobs_done:    21,
    years_exp:    7,
    daily_rate:   650,
    rating:       4.6,
  },
  {
    id: 'w3',
    full_name:    'Pedro Reyes',
    service:      'carpentry',
    verified:     true,
    ml_score:     52,
    skills:       ['Carpentry', 'Furniture', 'Roofing'],
    location:     'Zone 2, Bulua, CDO',
    availability: 'Weekends',
    jobs_done:    8,
    years_exp:    3,
    daily_rate:   500,
    rating:       4.5,
  },
  {
    id: 'w4',
    full_name:    'Carlo Mendez',
    service:      'welding',
    verified:     false,
    ml_score:     50,
    skills:       ['Welding'],
    location:     'Zone 3, Bulua, CDO',
    availability: 'Flexible',
    jobs_done:    0,
    years_exp:    1,
    daily_rate:   450,
    rating:       null,
  },
  {
    id: 'w5',
    full_name:    'Ben Torres',
    service:      'carpentry',
    verified:     true,
    ml_score:     50,
    skills:       ['Carpentry', 'Cabinet Making', 'Flooring', 'Doors'],
    location:     'Zone 5, Bulua, CDO',
    availability: 'Weekdays',
    jobs_done:    14,
    years_exp:    9,
    daily_rate:   600,
    rating:       4.9,
  },
  {
    id: 'w6',
    full_name:    'Ana Gomez',
    service:      'welding',
    verified:     true,
    ml_score:     50,
    skills:       ['Welding', 'Furniture Repair'],
    location:     'Zone 6, Bulua, CDO',
    availability: 'Flexible',
    jobs_done:    3,
    years_exp:    2,
    daily_rate:   550,
    rating:       4.2,
  },
  {
    id: 'w7',
    full_name:    'Mario Bautista',
    service:      'mason',
    verified:     true,
    ml_score:     62,
    skills:       ['Masonry', 'Tile Setting', 'Concrete Work'],
    location:     'Zone 7, Bulua, CDO',
    availability: 'Weekdays',
    jobs_done:    19,
    years_exp:    11,
    daily_rate:   580,
    rating:       4.7,
  },
  {
    id: 'w8',
    full_name:    'Lita Cruz',
    service:      'plumbing',
    verified:     true,
    ml_score:     44,
    skills:       ['Plumbing', 'Drain Cleaning'],
    location:     'Zone 8, Bulua, CDO',
    availability: 'Weekdays',
    jobs_done:    6,
    years_exp:    2,
    daily_rate:   400,
    rating:       4.3,
  },
];